


test('Try-Catch statement with error', (api) -> {
    var error
    
    try {
        api.throwError()
        api.fail()
    } catch e {
        error = e
    }
    
    api.is(error, 'object')
    api.is(error.constructor, "Error")
    api.done()
})

test('Try-Catch statement without error', (api) -> {
    var msg
    
    try
        api.dontThrowError()
        msg = 'no error'
    catch e do
        msg = e.message
        api.fail()
    
    
    api.eq(msg, 'no error')
    api.done()
})

test('Try-Finally statement with error', (api) -> {
    try {
        api.throwError()
    } finally {
        api.done()
    }

    api.fail()    
})

test('Try-Finally statement without error', (api) -> {
    try {
        api.dontThrowError()
    } finally {
        api.done()
    }

    api.fail()    
})

test('Try-Finally statement with error', (api) -> {
    try {
        api.throwError()
    } finally {
        api.done()
    }

    api.fail()    
})

test('Try-Catch-Finally without error', (api) -> {
    try {
        api.dontThrowError()
    } finally {
        api.done()
    }

    api.fail()    

})